sidebar:
  userName: "[Your Name]"
  profileImage: https://github.com/shadcn.png
  sections:
    - title: About Me
      url: "/"
      icon:
        name: User
        package: lucide-react

    - title: Projects
      url: "/projects"
      icon:
        name: Wrench
        package: lucide-react

    - title: Publications
      url: "/publications"
      icon:
        name: LibraryBig
        package: lucide-react

    - title: Articles
      url: "/articles"
      icon:
        name: Newspaper
        package: lucide-react

    - title: Movies
      url: "/movies"
      icon:
        name: Clapperboard
        package: lucide-react

    - title: Music
      url: "/music"
      icon:
        name: Music
        package: lucide-react
